name: Generate
on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  generate:
    name: Generate and publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        batch: [1,2,3,4,5,6,7,8,9]
      fail-fast: true
      max-parallel: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Fetch latest binary
        run: curl -L -O https://github.com/lauripiispanen/most-active-github-users-counter/releases/latest/download/github-top && chmod u+x github-top
      - name: Generate Batch
        run: ./generate_batch.sh ${{ matrix.batch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Add files to git
        run: git add .
      - name: Config git
        run: git config --local user.name "isyuricunha" && git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Commit
        run: >
          git update-index --refresh && git diff-index --quiet HEAD || git commit -m "Update data"
      - name: Push
        run: git push origin master
      - name: Trigger GitHub pages rebuild
        run: |
          curl --fail --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/pages/builds \
            --header "Authorization: Bearer $USER_TOKEN"
        env:
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
