name: Top GitHub Users
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
jobs:
  release:
    name: GitHub Active Users
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.CUSTOM_TOKEN }}

      - name: Set GitHub Actor
        run: echo "GITHUB_ACTOR=isyuricunha" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.17.0

      - name: Run Top GitHub Users Action
        uses: gayanvoice/top-github-users-action@master
        env:
          CUSTOM_TOKEN: ${{ secrets.CUSTOM_TOKEN }}
        with:
          branch: main
          commit_user_email: "115634315+isyuricunha@users.noreply.github.com"
          commit_author: isyuricunha <"115634315+isyuricunha@users.noreply.github.com">
